name: main

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requirements for current project
        run: sudo apt-get update && sudo apt-get -y install grep cmake build-essential g++ python3-pip clang-tidy libboost-test-dev grep

      - name: install cpplint
        run: pip install cpplint

      - name: use cpplint
        run: >
          find . \( -name '*.h' -or -name '*.cpp' \) -and -not -wholename '*/cmake-build/*' |
          xargs cpplint --counting=detailed  |
          grep -s -e "Category" -e "Total error"